export const GET_COIN_MARKET_DATA = 'GET_COIN_MARKET_DATA';
export const GET_COIN_MARKET_DATA_SUCCESS = 'GET_COIN_MARKET_DATA_SUCCESS';
export const GET_COIN_MARKET_DATA_FAIL = 'GET_COIN_MARKET_DATA_FAIL';